// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetAllUsers():Promise<Array<dto.UserListItem>>;

export function GetUserByID(arg1:number):Promise<dto.UserOutput>;

export function HasUsers():Promise<boolean>;

export function Login(arg1:dto.LoginInput):Promise<dto.UserOutput>;

export function Register(arg1:dto.RegisterInput):Promise<dto.UserOutput>;
