// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Create(arg1:dto.CreateClientInput):Promise<dto.ClientOutput>;

export function Delete(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<dto.ClientOutput>;

export function List():Promise<Array<dto.ClientOutput>>;

export function Update(arg1:dto.UpdateClientInput):Promise<dto.ClientOutput>;
