// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['services']['ClientService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['services']['ClientService']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['services']['ClientService']['Get'](arg1);
}

export function List() {
  return window['go']['services']['ClientService']['List']();
}

export function Update(arg1) {
  return window['go']['services']['ClientService']['Update'](arg1);
}
