// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['services']['ClientService']['Create'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['ClientService']['Delete'](arg1, arg2);
}

export function Get(arg1, arg2) {
  return window['go']['services']['ClientService']['Get'](arg1, arg2);
}

export function List(arg1) {
  return window['go']['services']['ClientService']['List'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['services']['ClientService']['Update'](arg1, arg2);
}
