// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Create(arg1:dto.CreateInvoiceInput):Promise<dto.InvoiceOutput>;

export function Delete(arg1:number):Promise<void>;

export function GeneratePDF(arg1:number):Promise<string>;

export function Get(arg1:number):Promise<dto.InvoiceOutput>;

export function List():Promise<Array<dto.InvoiceOutput>>;

export function SendEmail(arg1:number):Promise<boolean>;

export function Update(arg1:dto.UpdateInvoiceInput):Promise<dto.InvoiceOutput>;
