// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['services']['InvoiceService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['services']['InvoiceService']['Delete'](arg1);
}

export function GeneratePDF(arg1) {
  return window['go']['services']['InvoiceService']['GeneratePDF'](arg1);
}

export function Get(arg1) {
  return window['go']['services']['InvoiceService']['Get'](arg1);
}

export function List() {
  return window['go']['services']['InvoiceService']['List']();
}

export function SendEmail(arg1) {
  return window['go']['services']['InvoiceService']['SendEmail'](arg1);
}

export function Update(arg1) {
  return window['go']['services']['InvoiceService']['Update'](arg1);
}
