// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['services']['InvoiceService']['Create'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['InvoiceService']['Delete'](arg1, arg2);
}

export function GeneratePDF(arg1, arg2) {
  return window['go']['services']['InvoiceService']['GeneratePDF'](arg1, arg2);
}

export function Get(arg1, arg2) {
  return window['go']['services']['InvoiceService']['Get'](arg1, arg2);
}

export function List(arg1) {
  return window['go']['services']['InvoiceService']['List'](arg1);
}

export function SendEmail(arg1, arg2) {
  return window['go']['services']['InvoiceService']['SendEmail'](arg1, arg2);
}

export function Update(arg1, arg2) {
  return window['go']['services']['InvoiceService']['Update'](arg1, arg2);
}
