// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['services']['ProjectService']['Create'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['ProjectService']['Delete'](arg1, arg2);
}

export function Get(arg1, arg2) {
  return window['go']['services']['ProjectService']['Get'](arg1, arg2);
}

export function List(arg1) {
  return window['go']['services']['ProjectService']['List'](arg1);
}

export function ListByClient(arg1, arg2) {
  return window['go']['services']['ProjectService']['ListByClient'](arg1, arg2);
}

export function Update(arg1, arg2) {
  return window['go']['services']['ProjectService']['Update'](arg1, arg2);
}
