// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['services']['ProjectService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['services']['ProjectService']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['services']['ProjectService']['Get'](arg1);
}

export function List() {
  return window['go']['services']['ProjectService']['List']();
}

export function ListByClient(arg1) {
  return window['go']['services']['ProjectService']['ListByClient'](arg1);
}

export function Update(arg1) {
  return window['go']['services']['ProjectService']['Update'](arg1);
}
