// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Create(arg1:dto.CreateProjectInput):Promise<dto.ProjectOutput>;

export function Delete(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<dto.ProjectOutput>;

export function List():Promise<Array<dto.ProjectOutput>>;

export function ListByClient(arg1:number):Promise<Array<dto.ProjectOutput>>;

export function Update(arg1:dto.UpdateProjectInput):Promise<dto.ProjectOutput>;
