// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['services']['TimesheetService']['Create'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['TimesheetService']['Delete'](arg1, arg2);
}

export function Get(arg1, arg2) {
  return window['go']['services']['TimesheetService']['Get'](arg1, arg2);
}

export function List(arg1, arg2) {
  return window['go']['services']['TimesheetService']['List'](arg1, arg2);
}

export function Update(arg1, arg2) {
  return window['go']['services']['TimesheetService']['Update'](arg1, arg2);
}
