// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['services']['TimesheetService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['services']['TimesheetService']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['services']['TimesheetService']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['services']['TimesheetService']['List'](arg1);
}

export function Update(arg1) {
  return window['go']['services']['TimesheetService']['Update'](arg1);
}
