// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Create(arg1:dto.CreateTimeEntryInput):Promise<dto.TimeEntryOutput>;

export function Delete(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<dto.TimeEntryOutput>;

export function List(arg1:number):Promise<Array<dto.TimeEntryOutput>>;

export function Update(arg1:dto.UpdateTimeEntryInput):Promise<dto.TimeEntryOutput>;
