// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['services']['UserTaxSettingsService']['Get'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['services']['UserTaxSettingsService']['Update'](arg1, arg2);
}
